server:
  port: 8065

spring:
  application:
    name: DeviceManager
  mvc:
    servlet:
      path: /api
  datasource:
    url: jdbc:postgresql://localhost:5432/device_manager?currentSchema=device_manager
    username: postgres
    password: postgres
  liquibase:
    change-log: changelog/master-changelog.xml
    enabled: true
    default-schema: device_manager
    drop-first: false